canvas:
  width: 1080
  height: 1080
  image_offset_x: 0
  image_offset_y: 0

regions:

  title:
    x: 60
    y: 40
    width: 960
    height: 200
    font: title
    align: center
    valign: middle

  type:
    x: 60
    y: 260
    width: 960
    height: 100
    font: subtitle
    align: center
    valign: top

  datetime:
    x: 60
    y: 720
    width: 960
    height: 60
    font: body
    align: center
    valign: bottom

  dm:
    x: 60
    y: 790
    width: 960
    height: 60
    font: dm
    align: center
    valign: middle

  teaser:
    x: 100
    y: 860
    width: 880
    height: 190
    font: teaser
    align: center
    valign: middle

  credits:
    x: 30
    y: 1050
    width: 1020
    height: 30
    font: credits
    align: right
    valign: bottom